import firestore from '@react-native-firebase/firestore';

// Firestore collection reference
const usersCollection = firestore().collection('CardDetails');
const usersLoginCredentials = firestore().collection('LoginCredentials');

/**
 * 🔥 Create a user with a custom ID
 */
export const addUserWithAutoGeneratedID = async (
  CardHolder: string,
  CardNumber: string,
  ExDate: string,
  PinCode: string,
  SecretLable: string,
) => {
  try {
    await usersCollection
      .doc()
      .set({CardHolder, CardNumber, ExDate, PinCode, SecretLable});
    console.log('added sucessfuly');
  } catch (error) {
    console.error('Error adding user:', error);
  }
};

export const addLoginDataWithAutoGeneratedID = async (idToken: string) => {
  try {
    await usersLoginCredentials.doc().set({idToken});
    console.log('added sucessfuly');
  } catch (error) {
    console.error('Error adding user:', error);
  }
};

/**
 * 🔥 Create a user with an auto-generated ID
 */
export const addUserWithAutoID = async (name: string, age: number) => {
  try {
    const newDocRef = await usersCollection.add({name, age});
    console.log('User added with auto-generated ID:', newDocRef.id);
  } catch (error) {
    console.error('Error adding user:', error);
  }
};

/**
 * 📖 Read a single user by ID
 */
export const getUser = async (id: string) => {
  try {
    const user = await usersCollection.doc(id).get();
    if (user.exists) {
      console.log('User Data:', user.data());
      return user.data();
    } else {
      console.log('User not found!');
      return null;
    }
  } catch (error) {
    console.error('Error getting user:', error);
  }
};

/**
 * 📖 Read all users from Firestore
 */
export const getAllUsers = async () => {
  try {
    const snapshot = await usersCollection.get();
    console.log('hello');
    const users = snapshot.docs.map(doc => ({id: doc.id, ...doc.data()}));
    console.log('All Users:', users);
    return users;
  } catch (error) {
    console.error('Error getting users:', error);
  }
};

/**
 * ✏️ Update a user's data
 */
export const updateUser = async (
  id: string,
  newData: {name?: string; age?: number},
) => {
  try {
    await usersCollection.doc(id).update(newData);
    console.log('User updated!');
  } catch (error) {
    console.error('Error updating user:', error);
  }
};

/**
 * 🗑️ Delete a user from Firestore
 */
export const deleteUser = async (id: string) => {
  try {
    await usersCollection.doc(id).delete();
    console.log('User deleted!');
  } catch (error) {
    console.error('Error deleting user:', error);
  }
};
