import {Icon} from 'react-native-basic-elements';
import {SizeConfig} from '../../../components/SizeConfig';
import {
  Image,
  PixelRatio,
  Pressable,
  Text,
  TextInput,
  View,
} from 'react-native';
import {Gesture, GestureDetector} from 'react-native-gesture-handler';
import {
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
  withDelay,
  withTiming,
} from 'react-native-reanimated';
import {useEffect, useRef, useState} from 'react';
import analytics from '@react-native-firebase/analytics';

export const Headder = () => {
  return (
    <View
      style={{
        flexDirection: 'row',
        height: SizeConfig.height * 3,
        alignItems: 'center',
      }}>
      <Icon
        type="AntDesign"
        name="arrowleft"
        color={'black'}
        size={SizeConfig.width * 7}
        style={{position: 'absolute'}}
      />
      <Text
        style={{
          textAlign: 'center',
          flex: 1,
          fontSize: SizeConfig.fontSize * 5,
          fontFamily: 'RedHatDisplay-Medium',
        }}>
        Check Out
      </Text>
    </View>
  );
};

import React from 'react';
import Animated from 'react-native-reanimated';
import {AllCardDetails} from '../../../redux/slices/CardDetailsSlice';
import {useDispatch, useSelector} from 'react-redux';
import Carousel from 'react-native-reanimated-carousel';
import {RootState} from '../../../redux/Store';
import Snackbar from 'react-native-snackbar';
import {addUserWithAutoGeneratedID} from '../../../firebase/FireDaseDB';

const scaleFactor = PixelRatio.get();
export const CreditCardLayout = () => {
  const NexSection = useSharedValue<boolean>(false);
  const pressed = useSharedValue<boolean>(false);

  const [cardNo, setCardNo] = useState('');
  const [secretLable, setSecretLable] = useState('');
  const [cardHolder, setCardHolder] = useState('');
  const [exDate, setExDate] = useState('');
  const [pinCode, setPinCode] = useState('');
  const [pushNext, setPushNext] = useState(false);
  const [AddNewCard, setAddNewCard] = useState(false);
  const [isBtnPressed, setBtnPressed] = useState(false);

  let dispatch = useDispatch();

  const NextSectionTapGesture = Gesture.Tap()
    .runOnJS(true)
    .onBegin(() => {
      if (pushNext) {
        NexSection.value = pushNext ? true : false;
        runOnJS(setBtnPressed)(true);
      }
    });

  const HideSuccessMessage = useAnimatedStyle(() => ({
    opacity: NexSection.value
      ? withDelay(3000, withTiming(1, {duration: 1000})) // Fade in
      : withTiming(0, {duration: 500}), // Fade out

    position: NexSection.value ? 'relative' : 'absolute', // Keep out of layout flow when hidden

    zIndex: NexSection.value ? 1 : -1, // Send to back when hidden
  }));

  const ScaleSuccessMessageIcon = useAnimatedStyle(() => ({
    transform: [
      {
        scale: withDelay(
          3500,
          withTiming(
            NexSection.value ? SizeConfig.width * 0.19 : SizeConfig.width * 0,
            {
              duration: 500,
            },
          ),
        ),
      },
    ],
  }));

  const NextSectionAnimatedStyles = useAnimatedStyle(() => ({
    transform: [
      {
        translateX: withTiming(NexSection.value ? 0 : SizeConfig.width * 63, {
          duration: 1000,
        }),
      },
    ],

    width: withTiming(
      NexSection.value ? SizeConfig.width * 4 : SizeConfig.width * 13,
      {
        duration: 1000,
      },
    ),
    height: withTiming(
      NexSection.value ? SizeConfig.width * 4 : SizeConfig.width * 13,
      {
        duration: 1000,
      },
    ),

    borderRadius: withTiming(
      NexSection.value
        ? (SizeConfig.width * 13) / 2
        : (SizeConfig.width * 13) / 2,
      {
        duration: 1000,
      },
    ),
  }));

  const MakeLoadingVisible = useAnimatedStyle(() => ({
    opacity: NexSection.value
      ? withDelay(
          1500,
          withTiming(1, {
            duration: 500,
          }),
        )
      : withDelay(
          1000,
          withTiming(0, {
            duration: 500,
          }),
        ),
  }));
  const MakeLoadingColorVisible = useAnimatedStyle(() => ({
    backgroundColor: NexSection.value
      ? withDelay(
          1800,
          withTiming('#f86f15', {
            duration: 500,
          }),
        )
      : withDelay(
          1000,
          withTiming('gray', {
            duration: 500,
          }),
        ),
  }));

  const ChangingTheNextScreen = useAnimatedStyle(() => ({
    display: NexSection.value ? 'none' : 'flex',
  }));

  const ChangingTheNextScreenText = useAnimatedStyle(() => ({
    display: NexSection.value ? 'flex' : 'none',
  }));

  let StringSlicer = (name: string, index: number, lable: string) => {
    if (lable == 'cardNumber') {
      setCardNo(prev => prev + name[index]);
    } else if (lable == 'secretLable') {
      setSecretLable(prev => prev + name[index]);
    } else if (lable == 'cardHolder') {
      setCardHolder(prev => prev + name[index]);
    } else if (lable == 'exDate') {
      setExDate(prev => prev + name[index]);
    } else if (lable == 'pinCode') {
      setPinCode(prev => prev + name[index]);
    }
  };

  useEffect(() => {
    if (pushNext && isBtnPressed) {
      setTimeout(() => {
        dispatch(
          AllCardDetails({
            cardNo,
            secretLable,
            cardHolder,
            exDate,
            pinCode,
          }),
        );

        addUserWithAutoGeneratedID(
          cardNo,
          secretLable,
          cardHolder,
          exDate,
          pinCode,
        );

        NexSection.value = false;
        pressed.value = false;

        setCardNo('');
        setSecretLable('');
        setCardHolder('');
        setExDate('');
        setPinCode('');
        setPushNext(false);
        setAddNewCard(false);
        setBtnPressed(false);
      }, 5700);
    }
  }, [pushNext, isBtnPressed]);

  useEffect(() => {
    if (
      cardNo.length >= 16 &&
      secretLable.length &&
      cardHolder.length &&
      exDate.length &&
      pinCode.length
    ) {
      setPushNext(true);
    }
  }, [cardNo, secretLable, cardHolder, exDate, pinCode]);

  let StopTimer = (timeLock: NodeJS.Timeout) => {
    clearInterval(timeLock);
  };

  let timerFunction = (name: string, lable: string) => {
    let count = 0;
    let timeLock = setInterval(() => {
      if (count >= name.length) {
        StopTimer(timeLock);
        return;
      }
      StringSlicer(name, count, lable);
      count++;
    }, 10);
  };

  const tapGesture = Gesture.Tap()
    .runOnJS(true)
    .onBegin(() => {
      pressed.value = true;
    });

  const animatedStyles = useAnimatedStyle(() => ({
    transform: [
      {
        translateY: withTiming(
          cardNo.length >= 5 ? SizeConfig.width * 3 : -SizeConfig.width * 18,
        ),
      },
    ],
  }));

  const FillNewCardTapAnimatedStyle = useAnimatedStyle(() => ({
    transform: [
      {
        scale: withTiming(AddNewCard ? 1 : 0, {
          duration: 1000,
        }),
      },
    ],
  }));
  const ListOfCards = useAnimatedStyle(() => ({
    transform: [
      {
        scale: withTiming(!NexSection.value ? 1 : 0, {
          duration: 500,
        }),
      },
    ],
  }));

  let CardDetailsData = useSelector(
    (state: RootState) => state.CardDetailsSlice.list,
  );

  let CardNoRef = useRef<TextInput | null>(null);
  let secretLableRef = useRef<TextInput | null>(null);
  let cardHolderRef = useRef<TextInput | null>(null);
  let exDateRef = useRef<TextInput | null>(null);
  let pinCodeRef = useRef<TextInput | null>(null);

  return (
    <Carousel
      data={CardDetailsData}
      height={SizeConfig.height * 32}
      enabled={CardDetailsData?.length > 1}
      loop={false}
      width={SizeConfig.width * 100}
      style={{
        width: '100%',
        height: SizeConfig.height * 32,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
      }}
      mode="parallax"
      modeConfig={{
        parallaxScrollingScale: (SizeConfig.deviceWidth * 0.0035) / scaleFactor,
        parallaxAdjacentItemScale:
          (SizeConfig.deviceWidth * 0.0035) / scaleFactor,
        parallaxScrollingOffset: SizeConfig.width * 10,
      }}
      renderItem={({
        item,
        index,
      }: {
        item: {
          name?: string;
          cardNo: string;
          secretLable: string;
          cardHolder: string;
          exDate: string;
          pinCode: string;
        };
        index: number;
      }) => {
        {
          if (item?.name !== 'scr') {
            return (
              <Animated.View
                style={[
                  {
                    justifyContent: 'space-evenly',
                    paddingHorizontal: SizeConfig.width * 5,
                    paddingVertical: SizeConfig.width * 3,
                    overflow: 'hidden',
                    backgroundColor: 'black',
                    borderRadius: SizeConfig.width * 3,
                    height: SizeConfig.height * 28,
                    elevation: 10,
                    shadowColor: 'black',
                  },
                  ListOfCards,
                ]}>
                <View
                  style={{
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                  }}>
                  <View
                    style={{
                      width: SizeConfig.width * 53,
                    }}>
                    <Text
                      style={{
                        fontSize: SizeConfig.fontSize * 3,
                        fontFamily: 'RedHatDisplay-Medium',
                        color: 'white',
                      }}>
                      Enter Card Number
                    </Text>
                    <TextInput
                      value={item?.cardNo}
                      style={{
                        fontSize: SizeConfig.fontSize * 4,
                        fontFamily: 'RedHatDisplay-ExtraBold',
                        color: 'white',
                        borderBottomColor: 'white',
                        borderBottomWidth: 1,
                      }}
                    />
                  </View>
                  <View
                    style={{
                      width: SizeConfig.width * 27,
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}>
                    <Text
                      style={{
                        fontSize: SizeConfig.fontSize * 3,
                        fontFamily: 'RedHatDisplay-Medium',
                        color: 'white',
                      }}>
                      Secret Lable
                    </Text>
                    <TextInput
                      value={item?.secretLable}
                      style={{
                        fontSize: SizeConfig.fontSize * 4,
                        fontFamily: 'RedHatDisplay-Bold',
                        color: 'white',
                        borderBottomColor: 'white',
                        borderBottomWidth: 1,
                      }}
                    />
                  </View>
                </View>

                <View
                  style={{
                    width: SizeConfig.width * 50,
                  }}>
                  <Text
                    style={{
                      fontSize: SizeConfig.fontSize * 3,
                      fontFamily: 'RedHatDisplay-Medium',
                      color: 'white',
                    }}>
                    Card Holder
                  </Text>
                  <TextInput
                    value={item?.cardHolder}
                    style={{
                      fontSize: SizeConfig.fontSize * 4,
                      fontFamily: 'RedHatDisplay-Bold',
                      color: 'white',
                      borderBottomColor: 'white',
                      borderBottomWidth: 1,
                    }}
                  />
                </View>
                <View
                  style={{
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                  }}>
                  <View
                    style={{
                      width: SizeConfig.width * 28,
                    }}>
                    <Text
                      style={{
                        fontSize: SizeConfig.fontSize * 3,
                        fontFamily: 'RedHatDisplay-Medium',
                        color: 'white',
                      }}>
                      Ex Date
                    </Text>
                    <TextInput
                      value={item?.exDate}
                      style={{
                        fontSize: SizeConfig.fontSize * 4,
                        fontFamily: 'RedHatDisplay-Bold',
                        color: 'white',
                        borderBottomColor: 'white',
                        borderBottomWidth: 1,
                      }}
                    />
                  </View>
                  <View
                    style={{
                      width: SizeConfig.width * 20,
                    }}>
                    <Text
                      style={{
                        fontSize: SizeConfig.fontSize * 3,
                        fontFamily: 'RedHatDisplay-Medium',
                        color: 'white',
                      }}>
                      Pin Code
                    </Text>
                    <TextInput
                      value={item?.pinCode}
                      style={{
                        fontSize: SizeConfig.fontSize * 4,
                        fontFamily: 'RedHatDisplay-Bold',
                        color: 'white',
                        borderBottomColor: 'white',
                        borderBottomWidth: 1,
                      }}
                    />
                  </View>
                  <View
                    style={[
                      {
                        width: SizeConfig.width * 20,
                        alignItems: 'center',
                        justifyContent: 'center',
                        overflow: 'hidden',
                      },
                    ]}>
                    <Image
                      source={require('../../../assets/images/Home/visa.png')}
                      style={[
                        {
                          width: SizeConfig.width * 20,
                          height: SizeConfig.width * 10,
                          resizeMode: 'center',
                        },
                      ]}
                    />
                  </View>
                </View>
              </Animated.View>
            );
          } else {
            return (
              <View
                style={{
                  paddingHorizontal: SizeConfig.width * 2,
                }}>
                {!AddNewCard ? (
                  <View
                    style={[
                      {
                        height: SizeConfig.height * 28,
                        borderWidth: 1,
                        borderColor: '#f86f15',
                        borderRadius: SizeConfig.width * 3,
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: SizeConfig.height * 2,
                        elevation: 10,
                        backgroundColor: 'white',
                        shadowColor: '#f86f15',
                      },
                    ]}>
                    <Pressable
                      style={{
                        height: SizeConfig.width * 10,
                        width: SizeConfig.width * 10,
                        backgroundColor: '#f86f15',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: (SizeConfig.width * 10) / 2,
                      }}
                      onPress={() => {
                        setAddNewCard(true);
                      }}>
                      <Icon
                        type="AntDesign"
                        name="plus"
                        size={SizeConfig.width * 5}
                        color={'white'}
                      />
                    </Pressable>
                    <Text
                      style={{
                        fontSize: SizeConfig.fontSize * 5,
                        fontFamily: 'RedHatDisplay-Medium',
                        color: '#f86f15',
                      }}>
                      Add a new card
                    </Text>
                  </View>
                ) : (
                  <View>
                    <Animated.View
                      style={[
                        {
                          justifyContent: 'space-evenly',
                          paddingHorizontal: SizeConfig.width * 5,
                          paddingVertical: SizeConfig.width * 3,
                          overflow: 'hidden',
                          borderRadius: SizeConfig.width * 3,
                          height: SizeConfig.height * 28,
                        },
                        ChangingTheNextScreen,
                      ]}>
                      <View
                        style={{
                          flexDirection: 'row',
                          justifyContent: 'space-between',
                        }}>
                        <View
                          style={{
                            width: SizeConfig.width * 53,
                          }}>
                          <Text
                            style={{
                              fontSize: SizeConfig.fontSize * 3,
                              fontFamily: 'RedHatDisplay-Medium',
                              color: 'white',
                            }}>
                            Enter Card Number
                          </Text>
                          <TextInput
                            value={cardNo}
                            ref={CardNoRef}
                            inputMode="numeric"
                            style={{
                              fontSize: SizeConfig.fontSize * 4,
                              fontFamily: 'RedHatDisplay-ExtraBold',
                              color: 'white',
                              borderBottomColor: 'white',
                              borderBottomWidth: 1,
                            }}
                            onChangeText={text => {
                              // Remove any existing spaces
                              let newText = text.replace(/\s/g, '');

                              // Ensure only digits and max length 19 (16 digits + 3 spaces)
                              if (/^\d*$/.test(newText)) {
                                if (newText.length <= 16) {
                                  // Format text into groups of 4
                                  let formattedText = newText
                                    .replace(/(\d{4})/g, '$1 ')
                                    .trim();
                                  setCardNo(formattedText);
                                } else {
                                  if (secretLableRef.current) {
                                    secretLableRef.current.focus();
                                  }
                                }
                              }
                            }}
                            // onPress={() => {
                            //   timerFunction(
                            //     '0000 0000 0000 0000',
                            //     'cardNumber',
                            //   );
                            // }}
                          />
                        </View>
                        <View
                          style={{
                            width: SizeConfig.width * 20,
                          }}>
                          <Text
                            style={{
                              fontSize: SizeConfig.fontSize * 3,
                              fontFamily: 'RedHatDisplay-Medium',
                              color: 'white',
                            }}>
                            Secret Lable
                          </Text>
                          <TextInput
                            value={secretLable}
                            inputMode="numeric"
                            ref={secretLableRef}
                            style={{
                              fontSize: SizeConfig.fontSize * 4,
                              fontFamily: 'RedHatDisplay-Bold',
                              color: 'white',
                              borderBottomColor: 'white',
                              borderBottomWidth: 1,
                            }}
                            onChangeText={text => {
                              if (/^\d*$/.test(text)) {
                                if (text.length <= 3) {
                                  setSecretLable(text);
                                } else {
                                  cardHolderRef.current?.focus();
                                }
                              }
                            }}
                            // onPress={() => {
                            //   timerFunction('123', 'secretLable');
                            // }}
                          />
                        </View>
                      </View>

                      <View
                        style={{
                          width: SizeConfig.width * 50,
                        }}>
                        <Text
                          style={{
                            fontSize: SizeConfig.fontSize * 3,
                            fontFamily: 'RedHatDisplay-Medium',
                            color: 'white',
                          }}>
                          Card Holder
                        </Text>
                        <TextInput
                          value={cardHolder}
                          ref={cardHolderRef}
                          inputMode="text"
                          style={{
                            fontSize: SizeConfig.fontSize * 4,
                            fontFamily: 'RedHatDisplay-Bold',
                            color: 'white',
                            borderBottomColor: 'white',
                            borderBottomWidth: 1,
                          }}
                          onChangeText={text => {
                            if (/^[A-Za-z]+$/.test(text)) {
                              if (text.length <= 10) {
                                setCardHolder(text);
                              } else {
                                exDateRef.current?.focus();
                              }
                            }
                          }}
                          // onPress={() => {
                          //   timerFunction('Suhail S', 'cardHolder');
                          // }}
                        />
                      </View>
                      <View
                        style={{
                          flexDirection: 'row',
                          justifyContent: 'space-between',
                        }}>
                        <View
                          style={{
                            width: SizeConfig.width * 28,
                          }}>
                          <Text
                            style={{
                              fontSize: SizeConfig.fontSize * 3,
                              fontFamily: 'RedHatDisplay-Medium',
                              color: 'white',
                            }}>
                            Ex Date
                          </Text>
                          <TextInput
                            value={exDate}
                            ref={exDateRef}
                            inputMode="numeric"
                            style={{
                              fontSize: SizeConfig.fontSize * 4,
                              fontFamily: 'RedHatDisplay-Bold',
                              color: 'white',
                              borderBottomColor: 'white',
                              borderBottomWidth: 1,
                            }}
                            onChangeText={text => {
                              let newText = text.replace(/\D/g, '');

                              if (newText.length > 4) return;

                              if (newText.length > 2) {
                                newText =
                                  newText.slice(0, 2) + '/' + newText.slice(2);
                              }

                              let month = parseInt(newText.slice(0, 2), 10);
                              if (month < 0 || month > 12) {
                                Snackbar.show({
                                  text: 'Enter a valid month (01-12)',
                                  duration: 1000,
                                  action: {
                                    text: 'UNDO',
                                    textColor: 'red',
                                  },
                                });
                                return;
                              }

                              if (newText.length === 5) {
                                let year = parseInt(newText.slice(3), 10);
                                let currentYear =
                                  new Date().getFullYear() % 100;
                                if (year < currentYear) {
                                  Snackbar.show({
                                    text: 'Enter a valid expiration year',
                                    duration: 1000,
                                  });
                                  return;
                                } else {
                                  pinCodeRef.current?.focus();
                                }
                              }

                              setExDate(newText);
                            }}

                            // onPress={() => {
                            //   timerFunction('01/23', 'exDate');
                            // }}
                          />
                        </View>
                        <View
                          style={{
                            width: SizeConfig.width * 20,
                          }}>
                          <Text
                            style={{
                              fontSize: SizeConfig.fontSize * 3,
                              fontFamily: 'RedHatDisplay-Medium',
                              color: 'white',
                            }}>
                            Pin Code
                          </Text>
                          <TextInput
                            value={pinCode}
                            inputMode="numeric"
                            ref={pinCodeRef}
                            style={{
                              fontSize: SizeConfig.fontSize * 4,
                              fontFamily: 'RedHatDisplay-Bold',
                              color: 'white',
                              borderBottomColor: 'white',
                              borderBottomWidth: 1,
                            }}
                            onChangeText={text => {
                              if (/^\d*$/.test(text) && text.length <= 6) {
                                setPinCode(text);
                              }
                            }}
                            // onPress={() =>
                            //   timerFunction('03294', 'pinCode');
                            // }}
                          />
                        </View>
                        <GestureDetector gesture={tapGesture}>
                          <View
                            style={[
                              {
                                width: SizeConfig.width * 20,
                                alignItems: 'center',
                                justifyContent: 'center',
                                overflow: 'hidden',
                              },
                            ]}>
                            <Animated.Image
                              source={require('../../../assets/images/Home/visa.png')}
                              style={[
                                {
                                  width: SizeConfig.width * 20,
                                  height: SizeConfig.width * 10,
                                  resizeMode: 'center',
                                },
                                animatedStyles,
                              ]}
                            />
                          </View>
                        </GestureDetector>
                      </View>
                    </Animated.View>
                    <>
                      <Animated.View
                        style={[
                          {
                            height: SizeConfig.height * 28,
                            borderRadius: SizeConfig.width * 3,
                            alignItems: 'center',
                            justifyContent: 'center',
                            position: 'absolute',
                            width: '100%',
                            zIndex: -1,
                            backgroundColor: 'black',
                          },
                          FillNewCardTapAnimatedStyle,
                        ]}>
                        <View
                          style={{
                            flexDirection: 'row',
                            alignItems: 'center',
                            gap: SizeConfig.width * 13,
                            width: '100%',
                            justifyContent: 'center',
                            height: SizeConfig.height * 7,
                          }}>
                          <GestureDetector gesture={NextSectionTapGesture}>
                            <Animated.View
                              style={[
                                {
                                  backgroundColor: pushNext
                                    ? '#f86f15'
                                    : 'gray',
                                  width: SizeConfig.width * 13,
                                  height: SizeConfig.width * 13,
                                  borderRadius: (SizeConfig.width * 13) / 2,
                                  alignItems: 'center',
                                  justifyContent: 'center',
                                  overflow: 'hidden',
                                  zIndex: 10,
                                  transform: [
                                    {translateX: SizeConfig.width * 63},
                                  ],
                                },
                                NextSectionAnimatedStyles,
                              ]}>
                              {isBtnPressed ? (
                                ''
                              ) : (
                                <Icon
                                  type="AntDesign"
                                  name="arrowright"
                                  size={SizeConfig.width * 8}
                                  color={'white'}
                                />
                              )}
                            </Animated.View>
                          </GestureDetector>
                          <Animated.View
                            style={[
                              {
                                width: SizeConfig.width * 4,
                                height: SizeConfig.width * 4,
                                borderRadius: (SizeConfig.width * 4) / 2,
                                backgroundColor: 'gray',
                              },
                              MakeLoadingVisible,
                              MakeLoadingColorVisible,
                            ]}
                          />
                          <Animated.View
                            style={[
                              {
                                width: SizeConfig.width * 4,
                                height: SizeConfig.width * 4,
                                borderRadius: (SizeConfig.width * 4) / 2,
                                backgroundColor: 'gray',
                              },
                              MakeLoadingVisible,
                              MakeLoadingColorVisible,
                            ]}
                          />
                        </View>
                        <Animated.Text
                          style={[
                            {
                              fontSize: SizeConfig.fontSize * 4,
                              color: 'white',
                              fontFamily: 'RedHatDisplay-Bold',
                            },
                            ChangingTheNextScreenText,
                          ]}>
                          Verifying Your Card
                        </Animated.Text>
                      </Animated.View>

                      <Animated.View
                        style={[
                          {
                            backgroundColor: 'black',
                            borderRadius: SizeConfig.width * 3,
                            alignItems: 'center',
                            justifyContent: 'center',
                            height: SizeConfig.height * 28,
                            gap: SizeConfig.height * 2,
                          },
                          HideSuccessMessage,
                        ]}>
                        <Animated.View
                          style={[
                            {
                              backgroundColor: '#f86f15',
                              width: SizeConfig.width * 15,
                              height: SizeConfig.width * 15,
                              alignItems: 'center',
                              justifyContent: 'center',
                              borderRadius: (SizeConfig.width * 15) / 2,
                            },
                            ScaleSuccessMessageIcon,
                          ]}>
                          <Image
                            source={require('../../../assets/images/Home/tick.png')}
                            style={{
                              width: SizeConfig.width * 10,
                              height: SizeConfig.width * 10,
                              resizeMode: 'center',
                              tintColor: 'white',
                            }}
                          />
                        </Animated.View>
                        <Text
                          style={{
                            fontSize: SizeConfig.fontSize * 4,
                            color: 'white',
                            fontFamily: 'RedHatDisplay-Bold',
                          }}>
                          Successfully Added!
                        </Text>
                      </Animated.View>
                    </>
                  </View>
                )}
              </View>
            );
          }
        }
      }}
    />
  );
};

export const BillingDetails = () => {
  return (
    <View
      style={{
        gap: SizeConfig.height * 3,
        backgroundColor: 'white',
        padding: SizeConfig.width * 7,
        borderRadius: SizeConfig.width * 3,
        elevation: 10,
      }}>
      <Text
        onPress={async () => {
          try {
            await analytics().logEvent('dateis14', {
              name: 'suhail',
              person: 'good boy',
            });
            console.log('Event logged successfully!');
          } catch (error) {
            console.error('Error logging event:', error);
          }
        }}
        style={{
          fontFamily: 'RedHatDisplay-Bold',
          fontSize: SizeConfig.fontSize * 5,
          color: 'black',
        }}>
        Order Details
      </Text>
      <View>
        <View
          style={{
            flexDirection: 'row',
            justifyContent: 'space-between',
          }}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            Bonsal Plant
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
        <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            Plant Pot
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
        <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            Plant Soil
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
      </View>
      <View style={{alignItems: 'flex-end'}}>
        <View style={{flexDirection: 'row', gap: SizeConfig.width * 20}}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            Bonsal Plant
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
        <View style={{flexDirection: 'row', gap: SizeConfig.width * 20}}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            Plant Pot
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
        <View style={{flexDirection: 'row', gap: SizeConfig.width * 20}}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            Plant Soil
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Medium',
              fontSize: SizeConfig.fontSize * 4,
              color: 'black',
            }}>
            $38.99
          </Text>
        </View>
        <View
          style={{
            flexDirection: 'row',
            gap: SizeConfig.width * 20,
            paddingTop: SizeConfig.height * 2,
          }}>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Bold',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            Total
          </Text>
          <Text
            style={{
              fontFamily: 'RedHatDisplay-Bold',
              fontSize: SizeConfig.fontSize * 4.5,
              color: 'black',
            }}>
            $98.99
          </Text>
        </View>
      </View>
    </View>
  );
};
